import Head from "next/head";

import { Provider, useDispatch } from "react-redux";

import { Box, Button } from "@mantine/core";
import {
  AddToFirstButton,
  AddToSecondButton,
  FirstValue,
  SecondValue,
} from "~/components";
// 2: provide the store to react
import { store } from "~/store/store";
import { doNothing } from "~/store/store";

export default function Home() {
  const DoNothingButton = () => {
    const dispatch = useDispatch();

    return (
      <Button
        size="xl"
        onClick={() => {
          dispatch(doNothing());
        }}
      >
        Do Nothing
      </Button>
    );
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-slate-800">
        <div>
          <Provider store={store}>
            <Box p={10}>
              <Box sx={{ display: "flex" }}>
                <AddToFirstButton />
                <FirstValue />
              </Box>

              <Box mt={10} sx={{ display: "flex" }}>
                <DoNothingButton />
              </Box>
              <Box mt={10} sx={{ display: "flex" }}>
                <AddToSecondButton />
                <SecondValue />
              </Box>
            </Box>
          </Provider>
        </div>
      </main>
    </>
  );
}
